export const SCREEN_ROUTER = {
    MAIN: 'MAIN',
    AUTH: 'AUTH',
    SPLASH: 'SPLASH',
    MAIN_ADMIN: 'MAIN_ADMIN'
}
export const SCREEN_ROUTER_AUTH = {
    LOGIN: 'LOGIN',
    FORGOT_PASS: 'FORGOT_PASS',
    REGISTER: 'REGISTER'
};
export const SCREEN_ROUTER_APP = {
    HOME: 'HOME',
    PRODUCT:'PRODUCT',
    PUTCALENDAR:'PUTCALENDAR',
    NOTIFY: 'NOTIFY',
    USER: 'USER',
}