const images = {
  ic_back: require('./images/ic_back.png'),
  ic_Setting: require('./images/ic_Setting.png'),
  ic_User: require('./images/ic_User.png'),
  ic_Splash: require('./images/ic_Splash.png'),
  ic_Home: require('./images/ic_Home.png'),
  ic_Notification: require('./images/ic_Notification.png'),
  ic_Product: require('./images/ic_Product.png'),
  ic_PutCalender: require('./images/ic_PutCalender.png'),
  ic_Search: require('./images/ic_search.png'),
  img_Recoding: require('./images/Recording_Studio.jpg'),
  img_RecodingA: require('./images/Recording_Studio_1.jpg'),
  img_RecodingB: require('./images/Recording_Studio_3.jpg'),
  img_Equalizer: require('./images/img_Equalizer.jpg'),
  img_HeadPhone: require('./images/img_HeadPhone.jpg'),
  img_Mixer: require('./images/img_Mixer.jpg'),
  img_Audio: require('./images/img_Audio.jpg'),
  img_Turbor: require('./images/img_Turbor.jpg'),
  img_Wepcam: require('./images/img_Wepcam.jpg'),
  img_Cap_Ugreen: require('./images/img_Cap_Ugreen.jpg'),
  ic_Date: require('./images/ic_Oclock.png'),
  ic_Group: require('./images/ic_Group.png'),
  ic_Phone: require('./images/ic_Phone.png'),
  ic_Messenger: require('./images/ic_Messenger.png'),
  img_Map: require('./images/img_Map.png'),
  ic_LogoFacebook: require('./images/ic_LogoFacebook.png'),
  ic_LogoGoogle: require('./images/ic_LogoGoogle.png'),
  img_Gen3: require('./images/img_Gen3.jpg'),
  img_Headphone_akg: require('./images/img_Headphone_akg.jpg'),
  img_Icon_Upod: require('./images/img_Icon_Upod.jpg'),
  img_Mackie: require('./images/img_Mackie.jpg'),
  img_M_track: require('./images/img_M_Track.jpg'),
  ic_Send: require('./images/ic_send.png'),
  ic_IMG: require('./images/ic_IMG.png'),
  ic_SendMess: require('./images/ic_send1.png'),
  ic_ios_camera: require('./images/ic_ios_camera.png'),
  img_Avatar: require('./images/Avatar.jpg'),
  ic_ChangePass: require('./images/ic_ChangePass.png'),
  ic_InforUser: require('./images/ic_Infor_User.png'),
  ic_Language: require('./images/ic_Language.png'),
  ic_Logout: require('./images/ic_logout.png'),
  ic_Orderproduct: require('./images/ic_Orderproduct.png'),
  ic_BackRight: require('./images/ic_BackRight.png'),
  ic_invisible: require('./images/ic_invisible.png'),
  ic_visibility: require('./images/ic_visibility.png'),
  ic_Photo:require('./images/ic_Photo.png'),
  ic_ChangeUser:require('./images/ic_ChangeUser.png'),
  ic_date:require('./images/ic_date.png'),
  ic_Chat:require('./images/ic_chat.png'),
  ic_money:require('./images/ic_money.png'),
  ic_introduct:require('./images/ic_introduct.png'),
  ic_PhoneNumber:require('./images/ic_PhoneNumber.png'),
  ic_adress:require('./images/ic_adress.png'),
  ic_expant:require('./images/ic_expant.png'),
  ic_Content:require('./images/ic_Content.png'),
  ic_MessegaeAdd:require('./images/ic_MessegaeAdd.png'),
  ic_NotificationAdd:require('./images/ic_NotificationAdd.png')
};
export default images;
