const string = {
  home: 'Trang chủ',
  product: 'Sản phẩm',
  putcalender: 'Đặt lịch',
  notification: 'Thông báo',
  user: 'Tài khoản',
  search: ' Tìm kiếm sản phẩm',
  log_in: 'Đăng nhập',
  registration: 'Đăng ký',
  forgot_password: 'Quên mật khẩu',
  no_account: 'Chưa có tài khoản',
  sign_up_for_account: 'Đăng ký tài khoản',
  AccountEmail: 'Tên đăng nhập hoặc email',
  pass: 'Mật khẩu',
  name: 'Họ tên',
  city: 'Tỉnh/thành phố',
  confirm_password: 'Xác nhận mật khẩu',
  confirm: 'Xác nhận',
  select_province: 'Chọn tỉnh thành',
  header_forgot: 'Vui lòng nhập email của bạn để lấy lại mật khẩu',
  email: 'Email',
  cancle: 'Hủy',
  pleaseLogin: 'Vui lòng nhập tài khoản và mật khẩu để đăng nhập',
};
export default string;