const string = {
  home: 'Trang chủ',
  product: 'Sản phẩm',
  Chat: 'chat',
  ListChat:'Danh sách phòng thu',
  putcalender: 'Đặt lịch',
  notification: 'Thông báo',
  user: 'Tài khoản',
  search: ' Tìm kiếm sản phẩm',
  searchCalendar:'Tìm kiếm phòng thu',
  log_in: 'Đăng nhập',
  registration: 'Đăng ký',
  forgot_password: 'Quên mật khẩu',
  no_account: 'Chưa có tài khoản',
  sign_up_for_account: 'Đăng ký tài khoản',
  AccountEmail: 'Tên đăng nhập hoặc email',
  pass: 'Mật khẩu',
  name: 'Họ tên',
  phone: 'Số điện thoại',
  city: 'Tỉnh/thành phố',
  District:'Quận/Huyện',
  Address:'Địa chỉ chi tiết',
  Sex:'Gới tính',
  Birth_Day:'Ngày sinh',
  confirm_password: 'Xác nhận mật khẩu',
  confirm: 'Xác nhận',
  select_province: 'Chọn tỉnh thành',
  select_distric:'Chọn quận huyện',
  header_forgot: 'Vui lòng nhập email của bạn để lấy lại mật khẩu',
  email: 'Email',
  cancle: 'Hủy',
  pleaseLogin: 'Vui lòng nhập tài khoản và mật khẩu để đăng nhập',
  pleaseRegister: 'Vui lòng nhập tài khoản và mật khẩu để đăng ký',
  pleaseForgotPass: 'Vui lòng đăng nhập email để lấy lại mật khẩu',
  messenger: 'Nhập tin nhắn',
  information: 'Thông tin cá nhân',
  order: 'Đơn hàng',
  language: 'Ngôn ngữ',
  changepass: 'Đổi mật khẩu',
  logout: 'Đăng xuất',
  logoutmess: 'Bạn thực sự muốn đăng xuất ? ',
  calladmin: 'Bạn muốn gọi hỗ trợ 0364177852',
  old_password: 'Mật khẩu cũ',
  new_password: 'Mật khẩu mới',
  confirm_new_password: 'Xác nhận mật khẩu mới',
  update_avatar:"Cập nhật ảnh đại diện", 
  update_user:"Cập nhật thông tin",
  Adrees:"Địa chỉ chi tiết",
  Boy:"Nam",
  Girl:"Nữ",
  Update_Sucess:"Cập nhật thành công!",
  ChangePass_Sucess:"Đổi mật khẩu thành công",
  Not_Update:'Chưa cập nhật ',
  introduct:'Giới Thiệu phòng thu',
  callStudio:'Bạn muốn liên hệ phòng thu ',
  exit:'Thoát',
  Call:'Gọi',
  PutStudio:'Bạn muốn đặt lịch thu âm ',
  map:'Địa chỉ phòng thu ',
  help:'Xin chào anh/chị em có thể giúp được gì anh chị ạ ?',
  loadingMesse:"Đang tải tin nhắn",
  Intro:"Chào mừng bạn đến với ứng dụng đặt lịch phòng thu Hãy lựa chọn cách đăng nhập ",
  User:"Khách hàng",
  Messages:"Tin nhắn",
  InforStudio:"Thông tin phòng thu",
  UpdateIntroStudio:"Cập nhật giới thiệu phòng thu",
  Revenue:"Doanh Thu",
  UpdatePriceCalender:"Cập nhật giá đặt lịch",
  By_Week:'Theo ngày',
  By_Month:'Theo tháng',
  History_PutCalender:'Lịch sử đặt lịch',
  Old_price:'Giá cũ',
  New_Price:'Giá mới',
  Sales_Promotion:'Khuyến mại',
  Total_Revenue:'Tổng doanh thu',
  Result_Search:"Kết quả tìm kiếm",
  Search_User:"Nhập tên khách hàng",
  InforUser:"Thông tin khách hàng",
  Put_Sucess:"Đặt lịch thành công",
  UpdateFailde:"Cập nhật mật khẩu không thành công"
};
export default string;